### ISSUE TITLE
MQTT Client

### ISSUE THREAD

**Issue by kunalfleethawks** [aws-samples/aws-iot-enhanced-custom-authorizer-demo#13]
Hi,
I have followed everything as per the repository. Can you help me on how to connect to AWT IOT username-password using clients like MQTTX or any other? I am able to connect using mosquitto_pub but unable to replicate it using UI clients. 

Thanks
Kunal

**Comment by dave-malone** [comment]
Closing this as it is an old issue. If this is still an issue, please re-open.
