### ISSUE TITLE
MQTT username/password sample

### ISSUE THREAD

**Issue by rafaelargenta-picpay** [aws-samples/aws-iot-enhanced-custom-authorizer-demo#3]
Hi, we are trying to use custom authorizer using the MQTT Connect with username/password fields.

Can you provide some basic example of code from the connection configurations, a sample how to use the TLS + SNDI extension using a common MQTT Client or the aws sdk-v2 in java code for example.

Thanks

**Comment by dave-malone** [comment]
@rafaelargenta-picpay thanks for the feedback. We do have a few examples that we need to merge into this codebase. We will work on getting that done hopefully within the next week.

**Comment by Nxtra** [comment]
It would be awesome if you could add that username/password example.
Very much looking forward to building with this.

**Comment by massi-ang** [comment]
It is on my backlog. For the time being, you can check out this repo: https://github.com/massi-ang/aws-iot-custom-authorizer-sample

**Comment by massi-ang** [comment]
@Nxtra you can find the code in the mqtt-username-password branch

**Comment by massi-ang** [comment]
Code is now provided in the mqtt-username-password branch.

**Comment by Nxtra** [comment]
Awesome! Thanks.
