### ISSUE TITLE
Outdated information in README.md

### ISSUE THREAD

**Issue by gadams999** [aws-samples/aws-iot-enhanced-custom-authorizer-demo#33]
The documentation states:
> At the time of writing, these features are available as public Beta only in the us-east-1 / N. Virginia region of AWS.

As this has been released to all regions, recommend either removing or updating the text to reflect the current state of the [AWS IoT Custom authentication and authorization workflow](https://docs.aws.amazon.com/iot/latest/developerguide/custom-authentication.html).

**Comment by dave-malone** [comment]
Removed this line from the readme. Please let me know if you think there's anything else that needs to be updated.
